#!/bin/sh

sleep 5

# Only on Aurora
if [ "$(hostname)" = "Aurora.local" ]; then
    razer-battery-tray "viper" & disown
    /home/horo/horoScripts/hr-silentrgb & disown
    /usr/bin/steam-runtime %U & disown
    # openrgb --server & # spammed to many Network server started stuff
    # /home/horo/horoScripts/hr-keyboard-top &
fi

sleep 2
cd ~ 

/home/horo/horoScripts/hr-monitor-my-mic &
syncthing & disown


#/home/horo/horoScripts/hr-gpu-screenrecorder &
#yakuake &
#GDK_BACKEND=x11 /usr/bin/ulauncher --hide-window --no-window-shadow &
#kclockd & # was to test if my pc could wake from sleep with it... (without crashing...)
#/usr/bin/nextcloud -background &



