#!/bin/sh
/home/horo/horoScripts/.screenlayout/.scripts/shared_all_start

/home/horo/horoScripts/.screenlayout/.scripts/shared_tv_off

xrandr \
--output HDMI-0 --off \
--output DP-0 --primary --mode 2560x1440 --pos 0x0 --rotate normal --refresh 165 --brightness 1 \
--output DP-1 --off \
--output DP-2 --off \
--output DP-3 --off \
--output DP-4 --off \
--output DP-5 --off
# gaming and one_display is the same (linked)

sleep 0
pactl set-default-sink $(pactl list sinks short | grep -Po "[0-9]+\s(?=alsa_output.*6ch)")

/home/horo/horoScripts/.screenlayout/.scripts/shared_all_end
