#!/bin/sh

/home/horo/horoScripts/.screenlayout/.scripts/shared_tv_on
sleep 8

xrandr \
--output HDMI-0 --mode 1920x1080 --pos 4480x360 --rotate normal --refresh 60 --gamma 1.2 --brightness 1 \
--output DP-0 --primary --mode 2560x1440 --pos 1920x0 --rotate normal --refresh 60 --brightness 1 \
--output DP-1 --off \
--output DP-2 --off \
--output DP-3 --mode 1920x1080 --pos 0x360 --rotate normal --refresh 60 --gamma 1.25:1.3:1.3  --brightness 1 \
--output DP-4 --off \
--output DP-5 --mode 1920x1080 --pos 4480x360 --rotate normal --refresh 60 --gamma 1.32:1.25:1.25  --brightness 1

sleep 2
pactl set-default-sink $(pactl list sinks |& rg --multiline "Sink #(.*)\n.*\n.*\n.*GA104 High Definition Audio Controller Digital Stereo \(HDMI .\)" -o -r '$1')
