#!/bin/sh

/home/horo/horoScripts/.screenlayout/.scripts/shared_tv_on
sleep 8

xrandr \
--output HDMI-0 --primary --mode 1920x1080 --pos 0x0 --rotate normal --refresh 60 --gamma 1.1 --brightness 1 \
--output DP-0 --off \
--output DP-1 --off \
--output DP-2 --off \
--output DP-3 --off \
--output DP-4 --off \
--output DP-5 --off

sleep 2
pactl set-default-sink $(pactl list sinks |& rg --multiline "Sink #(.*)\n.*\n.*\n.*GA104 High Definition Audio Controller Digital Stereo \(HDMI .\)" -o -r '$1')
