#!/bin/sh
/home/horo/horoScripts/.screenlayout/.scripts/shared_all_start

/home/horo/horoScripts/.screenlayout/.scripts/shared_tv_on
sleep 8

xrandr \
--output HDMI-0 --mode 1920x1080 --pos 4480x308 --rotate normal --refresh 60 --gamma 1.2 --brightness 1 \
--output DP-0 --primary --mode 2560x1440 --pos 1920x0 --rotate normal --refresh 60 --brightness 1 \
--output DP-1 --off \
--output DP-2 --off \
--output DP-3 --mode 1920x1080 --pos 4480x308 --rotate normal --refresh 60 --gamma 1.32:1.25:1.25 --brightness 1 \
--output DP-4 --off \
--output DP-5 --mode 1920x1080 --pos 0x180 --rotate normal --refresh 60 --gamma 1.25:1.3:1.3 --brightness 1

sleep 6
pactl set-default-sink $(pactl list sinks short | grep -Po "[0-9]+\s(?=alsa_output.*hdmi.*2ch)")

/home/horo/horoScripts/.screenlayout/.scripts/shared_all_end
