#!/bin/sh

/home/horo/horoScripts/.screenlayout/.scripts/shared_tv_off

xrandr \
--output HDMI-0 --off \
--output DP-0 --primary --mode 2560x1440 --pos 0x0 --rotate normal --refresh 165 --brightness 1 \
--output DP-1 --off \
--output DP-2 --off \
--output DP-3 --off \
--output DP-4 --off \
--output DP-5 --off
# gaming and one_display is the same (linked)

sleep 0
pactl set-default-sink $(pactl list sinks |& rg --multiline  "Sink #(.*)\n.*\n.*\n.*CMI8788 \[Oxygen HD Audio\] \(CMI8786 \(Xonar DGX\)\) Pro$" -o -r '$1')
