#!/bin/sh
/home/horo/horoScripts/.screenlayout/.scripts/shared_all_start

xrandr \
--output HDMI-0 --off \
--output DP-0 --off \
--output DP-1 --mode 1920x1080 --pos 0x180 --rotate normal --refresh 60 --gamma 1.25:1.3:1.3 --brightness 0.15 \
--output DP-2 --off \
--output DP-3 --mode 1920x1080 --pos 4480x138 --rotate normal --refresh 60 --gamma 1.32:1.25:1.25 --brightness 0.15 \
--output DP-4 --primary --mode 2560x1440 --pos 1920x-190 --rotate normal --refresh 120 --brightness 0.08 \
--output DP-5 --off

/home/horo/horoScripts/.screenlayout/.scripts/shared_all_end
