#!/bin/sh

cd /home/horo/horoScripts/.screenlayout/.scripts/
./shared_all_start

./shared_tv_on
./shared_desk_power_on &
sleep 9

xrandr \
--output HDMI-0 --primary --mode 1920x1080 --pos 4480x138 --rotate normal --refresh 60 --gamma 1.2 --brightness 1 \
--output DP-0 --off \
--output DP-1 --mode 1920x1080 --pos 0x180 --rotate normal --refresh 60 --gamma 1.25:1.3:1.3 --brightness 1 \
--output DP-2 --off \
--output DP-3 --mode 1920x1080 --pos 4480x138 --rotate normal --refresh 60 --gamma 1.32:1.25:1.25 --brightness 1 \
--output DP-4 --mode 2560x1440 --pos 1920x-190 --rotate normal --refresh 60 --brightness 1 \
--output DP-5 --off

/home/horo/Repositories/animes/anime_watcher.py &

sleep 6
pactl set-default-sink "$(pactl list sinks | grep -oPz '(?<=Sink #)[0-9]+(?=(\n.*){3}Description: GA104 High Definition Audio Controller Pro 8)\n')"

./shared_all_end
