#!/bin/sh
/home/horo/horoScripts/.screenlayout/.scripts/shared_all_start

/home/horo/horoScripts/.screenlayout/.scripts/shared_tv_on
sleep 8

xrandr \
--output HDMI-0 --primary --mode 1920x1080 --pos 0x0 --rotate normal --refresh 60 --gamma 1.1 --brightness 1 \
--output DP-0 --off \
--output DP-1 --off \
--output DP-2 --off \
--output DP-3 --off \
--output DP-4 --off \
--output DP-5 --off

sleep 6
pactl set-default-sink "$(pactl list sinks | grep -oPz '(?<=Sink #)[0-9]+(?=(\n.*){3}Description: GA104 High Definition Audio Controller Pro 8)\n')"

/home/horo/horoScripts/.screenlayout/.scripts/shared_all_end
