encryption = "age"

[age]
    identity = "/home/horo/.config/chezmoi/age/key.txt"
    recipient = "age1nmplh8ag4ma64zhzk3rs5jt75s5zx50fnvhxx4ug9ellh9v39ylsjfyq9u"

[edit]
    command = "code"
    args = ["--wait", "--new-window"]

[diff]
    command = "meld"
    args = ["--diff", "{{ .Destination }}", "{{ .Target }}"]

[merge]
    command = "meld"
    args = ["{{ .Source }}", "{{ .Target }}", "{{ .Destination }}", "--output", "{{ .Destination }}"]

    #args = ["--auto-merge", "{{ .Destination }}", "{{ .Source }}", "{{ .Target }}", "--output", "{{ .Destination }}"]

    #command = "code"
    #args = ["--wait", "--new-window", "--diff", "{{ .Destination }}", "{{ .Source }}"]
    #args = [".Source:{{ .Source }}", ".Destination:{{ .Destination }}", ".Target:{{ .Target }}"]

[keepassxc]
    database = "/home/horo/keepass/chezmoi_secrets.kdbx"
    args = [ "-k", "/home/horo/.horo/horo.key", "--no-password"]
    prompt = false
