encryption = "age"

[age]
    identity = "/home/horo/.config/chezmoi/age/key.txt"
    recipient = "age1nmplh8ag4ma64zhzk3rs5jt75s5zx50fnvhxx4ug9ellh9v39ylsjfyq9u"

[edit]
    command = "code"
    args = ["--wait", "--new-window"]

[diff]
    command = "meld"
    args = [
            "{{ .Destination }}", "--label=\"(File in ~) DESTINATION ({{ .Destination }})\"", 
            "{{ .Target }}", "--label=\"(Virtual File) TARGET (Resulting File (after template eval of SOURCE))\""
    ]

[merge]
    command = "meld"
    args = [
        "{{ .Destination }}", "--label=\"(File in ~) DESTINATION ({{ .Destination }})\"",
        "{{ .Source }}", "--label=\"SOURCE (chezmoi git repo) ({{ .Source }})\"", 
        "{{ .Target }}", "--label=\"(Virtual File) TARGET (Resulting File (after template eval of SOURCE))\""
    ]

[keepassxc]
    database = "/home/horo/Synced/keepass/chezmoi_secrets.kdbx"
    args = [ "-k", "/home/horo/.horo/horo.key", "--no-password"]
    prompt = false
